name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip libncurses5 curl
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry install

    - name: Set up Buildozer and install Cython
      run: |
        pip install buildozer
        pip install cython  # Install Cython

    - name: Accept Android SDK licenses
      run: |
        sudo apt-get install -y lib32stdc++6 lib32z1
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        mkdir -p $ANDROID_HOME/licenses
        echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
        echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

    - name: Create bin directory
      run: mkdir -p bin

    - name: Build APK
      run: buildozer android debug

    - name: List APK files in bin directory
      run: ls -la bin/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: '**/*.apk'
        if-no-files-found: warn
