name: Build Kivy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev python3-pip zlib1g-dev libncurses5 libncurses5-dev libffi-dev libsqlite3-dev libssl-dev
          pip install --upgrade pip setuptools
          pip install cython buildozer python-for-android

      - name: Set up Android SDK and NDK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.android/sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d latest
          rm commandlinetools.zip
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.1.8937393"

      - name: Create bin directory
        run: mkdir -p bin

      - name: Build APK
        run: buildozer android debug

      - name: List APK files in bin directory
        run: ls -la bin/

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: '**/*.apk'
          if-no-files-found: warn
